### ISSUE TITLE
VideoAnalyzer: Microsoft.WindowsAzure.Storage.Blob Depreciated

### ISSUE THREAD

**Issue by rdurrance** [Azure-Samples/media-services-v3-dotnet#25]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [x ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>Installing Microsoft.WindowsAzure.Storage.Blob on NuGet

### Any log messages given by the failure
>It is Tagged as Depreciated in the NuGet store

### Expected/desired behavior
>This Example 

### OS and Version?
> Windows 10 1909

### Versions
> VS2019

### Mention any other details that might be useful
The way to access blobs and containers is different in the recommended package Microsoft.Azure.Storage.Blob. If a beginner were to try, to convert the code, it would be difficult for them to successfully troubleshoot any problems because it could be a program issue (with their modification of the code to suit their needs) or it could be the way they implemented Microsoft.Azure.Storage.Blob.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by johndeu** [comment]
Thanks for the submission @rdurrance !
We updated the Blob code - thanks @xpouyat !

Also updated versions of things and made a change to the config file to use "Location" instead of "Region" to match the portal and CLI output better.
