### ISSUE TITLE
FaceRedactorMode should be 'Combined'

### ISSUE THREAD

**Issue by dbristolms** [Azure-Samples/media-services-v3-dotnet#39]
https://github.com/Azure-Samples/media-services-v3-dotnet/blob/d0449c0c2557682fc8741c714cd37c75b0c6f097/VideoAnalytics/FaceRedactor/Program.cs#L112
For this sample to run without more code to submit two jobs line 112 should be changed to be 
mode: FaceRedactorMode.Combined,

Combined mode is what's actually referenced in the comment.

**Comment by johndeu** [comment]
Thanks David, checking that.

**Comment by johndeu** [comment]
Shoot, that was my fault... looks like I had it flipped by accident when testing something for a customer. Fixed
