### ISSUE TITLE
How to send a stream of bits instead of a video?

### ISSUE THREAD

**Issue by wilbercl** [Azure-Samples/media-services-v3-dotnet#49]
Hello good morning, I would like to know how to send a stream of bits instead of a video, using your SDK in Azure media services. Thanks!

**Comment by johndeu** [comment]
Only if it is in the RTMP streaming protocol.  That works fine with our live ingest for Live Events. 
Otherwise, you have to upload the stream of bits into a blob file if you want to just do encoding of the file to another file format.

**Comment by wilbercl** [comment]
Thank you!!
