### ISSUE TITLE
How to streaming from an .avi container without encoding it in H264 or H265

### ISSUE THREAD

**Issue by wilbercl** [Azure-Samples/media-services-v3-dotnet#57]
Hello, I would like to stream a .avi container and not use any codec in the encoding process, that is, I do not want it to encode in H264 or H265, just upload the video and do not encode it, I am using the Azure SDK media services in .NET. the presets that azure media services has for example in their sdk, they all use h264 or h265 to encode and return an mp4, I just want to upload .avi and see if it is possible that it does not apply any compression and then download the .avi
Thanks!

**Comment by wilbercl** [comment]
I simply want to use the preset that Azure media services uses but that when I use h264 to encode I do it without loss, that is, crf 0

**Comment by xpouyat** [comment]
Hello,
I don't think can stream without encoding the video stream. Bitrate will be too high and there is no such support in adaptive streaming formats. H.264 and H.265 are lossy codecs, which means data is compressed in a lossy mode. Can you explain why you don't want a lossy compression ?

**Comment by wilbercl** [comment]
I want to stream an mp4 that I have built, and the information it has is correct, I do not want more bytes to be lost than it has, so when applying the sdk of azure media services, which uses h264 it is compressing me and I am losing bytes that I won't know how to rebuild later (I can't give many details of what the video contains, it's something confidential of the project I'm working on), my question is, can you use the azure media services SDK, where when coding do it with crf = 0, that is, encode without loss ???

**Comment by johndeu** [comment]
Closing this issue for now since it is stale.  There is no support for lossless encoding in AMS, and we do not support streaming anything other than content that is in H264 or HEVC encoded format at this time.
